# Docs: https://aka.ms/yaml

name: $(Build.DefinitionName)_$(Date:yyyyMMdd))
pr:
- master

pool: Hosted Windows 2019 with VS2019

steps:
- powershell: add-printerport -name "NUL:"
  displayName: 'add printer port'

- powershell: Add-Printer -name "MyDummyPrinter" -Drivername "Microsoft XPS Document Writer v4" -portname "NUL:"
  displayName: 'install dummy printer'

- powershell: .\prtg_sensor-spooler.ps1
  displayName: 'PRTG Sensor Windows Spooler'
  env:
    prtg_host: localhost
    cimprotocol: DCOM